if RUBY_VERSION =~ /1.9/
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
end

source 'https://rubygems.org'

gem 'eventmachine', '>=1.0.3', :git => 'https://github.com/eventmachine/eventmachine.git'
gem 'em-eventsource' , '>=0.2', :git => 'https://github.com/WhiskeyBravo/em-eventsource.git', :branch => 'patch-1'
gem 'em-http-request'
gem 'multi_json'
gem 'pry'
